services:

    dz.slack.identity_bag:
        class: DZunke\SlackBundle\Slack\Messaging\IdentityBag
        public: true

    dz.slack.connection:
        class: DZunke\SlackBundle\Slack\Client\Connection
        public: true

    dz.slack.client:
        class: DZunke\SlackBundle\Slack\Client
        public: true
        arguments: ["@dz.slack.connection"]

    dz.slack.messaging:
        class: DZunke\SlackBundle\Slack\Messaging
        public: true
        arguments: ["@dz.slack.client", "@dz.slack.identity_bag"]

    dz.slack.channels:
        class: DZunke\SlackBundle\Slack\Channels
        public: true
        arguments: ["@dz.slack.client"]

    dz.slack.users:
        class: DZunke\SlackBundle\Slack\Users
        public: true
        arguments: ["@dz.slack.client"]

    DZunke\SlackBundle\Slack\Messaging\IdentityBag: '@dz.slack.identity_bag'

    DZunke\SlackBundle\Slack\Client\Connection: '@dz.slack.connection'

    DZunke\SlackBundle\Slack\Client: '@dz.slack.client'

    DZunke\SlackBundle\Slack\Messaging: '@dz.slack.messaging'

    DZunke\SlackBundle\Slack\Channels: '@dz.slack.channels'

    DZunke\SlackBundle\Slack\Users: '@dz.slack.users'

    DZunke\SlackBundle\Command\BotMessagingCommand:
        class: DZunke\SlackBundle\Command\BotMessagingCommand
        arguments: ["@dz.slack.channels", "@event_dispatcher"]
        tags:
            - { name: console.command, command: slack:run-bot }

    DZunke\SlackBundle\Command\ChangeChannelsTopicCommand:
        class: DZunke\SlackBundle\Command\ChangeChannelsTopicCommand
        arguments: ["@dz.slack.channels"]
        tags:
            - { name: console.command, command: slack:channels:topic }

    DZunke\SlackBundle\Command\DebugCommand:
        class: DZunke\SlackBundle\Command\DebugCommand
        arguments: ["@dz.slack.client"]
        tags:
            - { name: console.command, command: slack:debug }

    DZunke\SlackBundle\Command\MessageCommand:
        class: DZunke\SlackBundle\Command\MessageCommand
        arguments: ["@dz.slack.messaging"]
        tags:
            - { name: console.command, command: slack:message }

    DZunke\SlackBundle\Command\UsersCommand:
        class: DZunke\SlackBundle\Command\UsersCommand
        arguments: ["@dz.slack.users"]
        tags:
            - { name: console.command, command: slack:users }
